# one step finish all including environment installation, working code deployment, webserver start
- name: Create Working directory on remote
  hosts: app
  sudo: yes
  vars:
    DIR: /cloud_asg

  tasks:
  - name: Create main working directory
    file: path={{DIR}} state=directory


