- name: Deploy tweet harvest scripts on remote working directory
  hosts: app
  sudo: yes
  vars:
    LOCAL_MAIN: ../../../../
    REMOTE_MAIN: /cloud_asg

  tasks:
# deploy harvest script
  - name: unzip tweet harvest script that coordinate with the default couchdb
    unarchive: src={{LOCAL_MAIN}}/harvest.zip dest={{REMOTE_MAIN}}/

# start harvest
  - name: start harvest tweet in to default couchdb
    command: sh start.sh chdir={{REMOTE_MAIN}}/harvest

