---
- name: Install the software package in clound VMS
  hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Update the cache
    apt: update_cache=yes
  - name: Install apache2
    apt: pkg=apache2 state=latest
  - name: Install curl
    apt: pkg=curl state=latest
  - name: Install pip
    easy_install: name=pip state=latest
  - name: Install couchDB
    apt: pkg=couchdb state=latest
  - name: Install python-couchDB
    apt: pkg=python-couchdb state=latest
  - name: Install tweepy
    pip: name=tweepy state=latest
  - name: Install nltk
    pip: name=nltk state=latest
  - name: Install textblob
    pip: name=textblob state=latest
  - name: Install googlemaps
    pip: name=googlemaps state=latest 
  - name: Install genderizer
    pip: name=genderizer state=latest 
  - name: Install pymongo
    pip: name=pymongo state=latest 
  - name: Install naiveBayesClassifier
    pip: name=naiveBayesClassifier state=latest 
  - name: Install python-memcached
    pip: name=python-memcached state=latest

# mount the volume with instances
  - name: create an ext4 partition
    filesystem: fstype=ext4 dev=/dev/vdc
  - name: create a directory for data
    file: path=/mnt/data state=directory
  - name: mount the volums
    mount: name=/mnt/data src=/dev/vdc fstype=ext4 state=mounted

# configuration for couchdb
  - name: create a directory for database
    file: path=/mnt/data/Project state=directory
  - name: copy couchdb directory
    shell: cp -R -p /var/lib/couchdb /mnt/data/Project/cloudCD
  - name: change port number
    lineinfile: dest=/etc/couchdb/local.ini
                regexp='^;port'
                insertafter="[httpd]"
                line="port = 5984"
  - name: change bind_address
    lineinfile: dest=/etc/couchdb/local.ini
                regexp='^;bind_address'
                insertafter=";port"
                line="bind_address = 0.0.0.0"

  - name: add directory for directory
    lineinfile: dest=/etc/couchdb/local.ini
                regexp="^database_dir"
                insertafter="^uuid"
                line="database_dir = /mnt/data/Project/cloudCD\nview_index_dir = /mnt/data/Project/cloudCD"
  - name: write access directory in alias
    lineinfile: dest=/etc/apparmor.d/tunables/alias
                regexp=''
                insertafter=EOF
                line="alias /var/lib/couchdb/ -> /mnt/data/Project/cloudCD/,"
  - name: restart a service couchdb
    service: name=couchdb state=restarted
